<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._VJwc2Z' shared service.

return $this->privates['.service_locator._VJwc2Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'dateCalculator' => ['privates', 'App\\Service\\DateCalculator', 'getDateCalculatorService.php', true],
    'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
], [
    'dateCalculator' => 'App\\Service\\DateCalculator',
    'logger' => '?',
]);
