<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0X.n9xH' shared service.

return $this->privates['.service_locator.0X.n9xH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\IndexController::home' => ['privates', '.service_locator._VJwc2Z', 'get_ServiceLocator_VJwc2ZService.php', true],
    'App\\Controller\\IndexController:home' => ['privates', '.service_locator._VJwc2Z', 'get_ServiceLocator_VJwc2ZService.php', true],
], [
    'App\\Controller\\IndexController::home' => '?',
    'App\\Controller\\IndexController:home' => '?',
]);
