<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\DateCalculator' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\DateCalculator.php';

return $this->privates['App\\Service\\DateCalculator'] = new \App\Service\DateCalculator();
